### ISSUE TITLE
Possible error on Mac OS X Mojave?

### ISSUE THREAD

**Issue by datadata95** [rse/vingester#1]
Javascript error in the main process, which prevents the app from even starting. Ocurres when trying to open the Vingester 1.0.0
![Skärmavbild 2021-04-01 kl  09 51 43](https://user-images.githubusercontent.com/69867381/113262146-94aab380-92d0-11eb-9745-8c0416c5fadc.png)

**Comment by rse** [comment]
Thanks for the detail. Yes, indeed, the underlying Grandiose NDI SDK bindings had linking bugs under Linux and macOS and just worked under Windows. I've not seen this bug myself, as I have the NDI SDK globally installed. This is now fixed. The new Vingester 1.0.1 now has these newer bindings and as a result should now working fine under macOS and Linux.
