### ISSUE TITLE
Vingester performance (vs Google Chrome)

### ISSUE THREAD

**Issue by Gabriele-LS** [rse/vingester#10]
Hello @rse. I just discovered Vingester uses much more CPU than Google Chrome.

<img width="1792" alt="Screenshot 2021-04-11 at 16 36 11" src="https://user-images.githubusercontent.com/67373152/114308600-d31c4b80-9ae4-11eb-9e98-ca00c8851518.png">

<img width="1792" alt="Screenshot 2021-04-11 at 16 39 29" src="https://user-images.githubusercontent.com/67373152/114308610-d6afd280-9ae4-11eb-94d5-09cc02708537.png">

During my tests, I also noted that the YouTube UI is smaller on Vingester than on Chrome. And, in Vingester, YouTube videos play with 480p resolution by default. Could that be something related to Retina displays resolution?

**Comment by rse** [comment]
Hmmm.. that's interesting. With your particular frameless setup (GPU enabled, no preview, etc) I also would expect that the overload CPU load is more or less equal. Hmmm... I've to check this.

BTW, for embedding YouTube Videos the best is to use the URLs like youtube.com/embed/<id>?autoplay=1

**Comment by rse** [comment]
I think I found already one reason for the lower performance. Even in frameless mode the frames capturing internally is enabled (even if it doesn't do anything). I guess this slows down Chrome dramatically. Will be addressed in 1.5.1 soon.

**Comment by Gabriele-LS** [comment]
Thanks for the tip about the YT URL. I look forward to testing version 1.5.1.

**Comment by rse** [comment]
OK, in Vingester 1.5.1 this performance problem should be no longer existing (at least not such dramatically). Can you retest with this newer version (just press the cloud icon in the top right corner of the control UI to update your executable).

**Comment by Gabriele-LS** [comment]
The situation is much better now. Thanks!

<img width="1242" alt="Screenshot 2021-04-11 at 19 16 30" src="https://user-images.githubusercontent.com/67373152/114314374-a83cf200-9afa-11eb-83b0-367ae7a164e1.png">
