### ISSUE TITLE
Interface issues: Dragging Windows and  Fullscreen projection

### ISSUE THREAD

**Issue by JBraddockm** [rse/vingester#11]
Since the standard traffic lights are removed, I can’t find a way to move/drag windows in frameless mode. I’ve tried different key combinations and click zones to ensure that I am not missing something but I can’t seem to find it. 

In addition to this, as I noted previously, even if I project a session onto a display via @+1,0 with the correct screen resolution set in Size, it doesn’t become a full screen due to menu bar. I have to manually go fullscreen. 

Secondly, I have to put the resolution in Size twice as high due to a Retina display. For example, for a 1080p display, I have to put 4K resolution as the size. 

I was wondering if these two are expected behaviours and/or a known limitations.

**Comment by rse** [comment]
It is intended that the browser windows cannot be moved or resized, as they should stay fixed (they are intended to be screen captured) and are controlled by the Vingester control UI only.

The issue with the menu bar can be an OS issue. Under what OS is this (Windows, macOS or Linux)? Under Windows one at least can configure that on non-primary displays no menubar exists at all. I'm not sure whether I can place the windows on top of the menu bar without any fullscreen mode. I'll check this.

The resolution issue is intended, I think. What does a 1080p display mean for you? Vingester adjusts the browser windows to the actual pixel resolution. So, if you have an external display with 4K physical resolution and you use a 200% OS display zoom, you can open 1080p there in full-screen, of course. But your pixels are doubled actually. Vingester's browser are intended to be screen-captured, so it would make no sense to capture doubled pixels. So, Vingester on such displays uses the physical size of 1080p and on a 4K physical display this is not fullscreen, of course. But I see no reason why you want to use a fullscreen window if you just want to capture 1080p. Just use 1920x1080 as the window size. Keep in mind that your display seems to have more physical resolution and you seem to have an OS display zoom configured there.

**Comment by JBraddockm** [comment]
I can see the intention behind the current design. However, I am not using screen-capturing but rather using ATEM Mini Pro to bring in a guess, which is also the reason why I use the fullscreen image.

I think the way I want to use the software and how it is intended to be used contradicts each other in some cases. For example, I don't mind having a fullscreen button but I understand why it could be a problem for others. Same for being able to drag the window.

In regards to the menu bar, on Mac, the only way to disable the menu bar on external displays is to disable "Display have separate Spaces" under Mission Control. However, doing so causes the internal screen to go black if you fullscreen an app on the external display. So in this sense, it is not practical. 

As I'd mentioned before, I am occasionally using QLab, which is able to project fullscreen images on the external screen and also on top of the menu bar without manually going fullscreen. The only reason I bring the dragging issue and fullscreen icons into the discussion is really due to this limitation of not being able to project fullscreen completely. Otherwise, I also don't see any reason for these options.

On the question of resolution. On QLab again, I only need to enter the actual resolution of the external display i.e 1920x1080 to project a fullscreen imagine onto it. It seemed counter-intuitive to enter 4K resolution as the size in Vingester, which I thought could be a bug. It is not a big issue but just a small thing I was curious about.

**Comment by rse** [comment]
What I could do is to provide a "fullscreen" option for display a window which internally queries the size of the external display and then use this size implicitly. For the menubar issue I've to check what I can do. Perhaps the underlying Electron technology provides a way to move the window on top of the menu bar in some way. But if I understand you correctly, the be able to more easily specify full-screen resolution and to getting rid of the menubar would be sufficient, right? And the reason for you is because you are sending the output of the external display through ATEM Mini Pro for capturing and there you need the browser window to full the physical size of the display, right?

**Comment by JBraddockm** [comment]
Correct. This is the only reason why I mention fullscreen button, dragging etc. Otherwise, If I can get a complete fullscreen projection on an external display, I have no use for fullscreen button, window dragging etc.

Thank you.

**Comment by rse** [comment]
I checked the code and I think what you want can already be achieved through the "Pin Top" configuration toggle. Because if you enable this, the window is pinned to the top and according to the Electron documentation this should place the window even over the menubar. Can you check this?

**Comment by JBraddockm** [comment]
Unfortunately, it doesn't have any effect on the fullscreen. The menubar still remains visible.

**Comment by rse** [comment]
Thanks for testing. I've checked the source code and the Electron documentation once again: you're right. It was still not correctly implemented by me. It should be now fixed in Vingester 1.5.3. Can you re-check with 1.5.3? There you should be now able to finally achieve the fullscreen effect with the help of the "Pin Top" toggle.

**Comment by JBraddockm** [comment]
I tested it and yes, it is working as expected. 

In fact, it is working too well :) I initially didn't have the external display connected so I tested it on the internal display. But then I noticed that there was no way to exit the window or change to another application. The fullscreen window always blocks others. CMD+Tab or other multitasking gestures also don't work. I had to log out to cancel the fullscreen.

Perhaps for the internal display, there could be a way to cancel the complete fullscreen image. Maybe an odd key combination or long-press on certain keys.

Thank you.

**Comment by rse** [comment]
Oh, I understand. Yes, I'll add a global hotkey for stopping all browsers or something like this...

**Comment by rse** [comment]
Ok, as a "rescue" option there is now a global hotkey CTRL+ALT+SHIFT+ESCAPE which you can press to stop all running browsers. Will be available with Vingester 1.5.6.

**Comment by rse** [comment]
Let's keep this issue open for the dragging request.

**Comment by JBraddockm** [comment]
In addition to this global hotkey that stops all sessions as well as quitting Vingester, can I suggest two additional hotkeys? 

One would stop all sessions but keep Vingester running, which I think CTRL+ALT+SHIFT+ESCAPE [CMD+Option+Shift+ESC on Macs] should actually do. The other one would stop the active session only. By active I mean the one I hover over and click on, which I think makes them "active" in Vingester app.

As for the dragging, do you think it makes sense to create a dragging zone where the traffic lights buttons were?

**Comment by rse** [comment]
The CTRL+ALT+SHIFT+ESCAPE will just stop the sessions and not quit Vingester. So, it will be the way you expect it. The dragging zone is not possible on the other hand, because the browser windows contain just the Web Contents and the traffic light buttons where an internal special feature of the operating system and not of the Electron app itself. I cannot overlay and dragging zone or buttons there from within Vingester.

**Comment by JBraddockm** [comment]
I think it might be a bug then. Because if I use the hotkey to stop sessions, it also quits Vingester.

**Comment by rse** [comment]
But how have you checked this? The CTRL+ALT+SHIFT+ESCAPE is just implemented but will be usable with the forthcoming Vingester 1.5.6 the first time. With the current 1.5.5 the hotkey still does not exist. So, if were able to already press the hotkey something else forced Vingester to quit?

**Comment by JBraddockm** [comment]
Hmm. I mistakenly assume it is available in 1.5.5. Still, CMD+Option+Shift+ESC stops all sessions and quits the app. But I don't think this is a bug in the app. It seems that CMD+Option+ESC is the default shortcut for Force Quit on Mac and when I add the Shift to the combination, it executes the force command without the Force Quit menu appearing. 

I can also quit the app that has active sessions with CMD+Q but I assume it is intended. This is confusing, however, because I am pretty sure I tried to quit the app with CMD+Q when I was testing the fullscreen projection and it wasn't working. 🙄

**Comment by rse** [comment]
With all the recent changes (rescue hotkey, window z-index ordering over dock, correct display zoom determination, etc) this issue should be solved at least to some extend, I think.
