### ISSUE TITLE
Window size issue

### ISSUE THREAD

**Issue by Gabriele-LS** [rse/vingester#14]
Hello @rse, I just discovered that Vingester has some issues in correctly sizing its browser windows. My main monitor is the internal retina display of my MacBook Pro, and I have two external 1080p monitors. When I set Vingester to display a 1920x1080 pixel browser window on monitor "-1,0", the size of the resulting window is a quarter of the monitor size.

![Screenshot 2021-04-13 at 12 16 07 (3)](https://user-images.githubusercontent.com/67373152/114538096-42b04900-9c53-11eb-89e1-01833c364400.png)

<img width="972" alt="Screenshot 2021-04-13 at 12 16 36" src="https://user-images.githubusercontent.com/67373152/114538115-493ec080-9c53-11eb-8bd3-78077a3146e8.png">

**Comment by luisfontes** [comment]
I had this issue on Windows10 and "fixed" it by disabling the scaling in display settings (image below), from 125% to 100%.

![](https://img.mywindowshub.com/images9/Focusassist-10.jpg)

**Comment by rse** [comment]
I think the DPI on the external displays is incorrectly calculated. I've to check this in more detail.

**Comment by rse** [comment]
This is now fixed (see commit 0e383a5) and will be available with Vingester 1.5.5 in a few minutes.
