### ISSUE TITLE
Browsers without a title are impossible to start, except when you use the global start button

### ISSUE THREAD

**Issue by Gabriele-LS** [rse/vingester#15]
Hello @rse, I just discovered I cannot start a browser instance if its title field is empty. But the global start button (the one close to the top of the Vingester window) is able to start that instance no matter if the title field empty or not.

**Comment by rse** [comment]
That it is not possible to start without a title is intentional. but the global start has a bug. It should also skip those browser instances. I'll fix this. Thanks for reporting this issue.

**Comment by rse** [comment]
Now fixed in the next version (1.5.5)
