### ISSUE TITLE
Ffmpeg RTMP output

### ISSUE THREAD

**Issue by aloproducao** [rse/vingester#18]
Hello, congratulations on the incredible project, it would be great if there was a direct output from it to rtmp without the need to use obs Studio for example.

**Comment by rse** [comment]
If Vingester will support outbound WAN connections, beside RTMP the SRT protocol would be another candidate to support...

**Comment by aloproducao** [comment]
I think it has the potential to replace obs for streaming as a viable alternative, for example an obs.ninja output for rtmp youtube.

chromium offers a very stable call better than the browser souce of obs studio, a direct output to rtmp is very powerful.

Thank you for the beautiful debate.

**Comment by rse** [comment]
Ah, ok. Understood, you want to get rid of the mixing at all. For some particular use-cases this might be sufficient, yes. On the other hand, it was also requested to provide a recording functionality. When I would add FFmpeg as a sink, Vingester could provide both things: recording and streaming. A basic cut-through I've already working, but I've still video/audio sync issues in this prototype. But Vingester is at least already able to record the video/audio and to stream it via RTMP. But it's still not released. It's just a cut-through and needs more stabilization and bugfixing before I could provide this in a release version.

**Comment by aloproducao** [comment]
This will be great, I look forward to this version, I am available to help

**Comment by rse** [comment]
Vingester 1.8.0 in its "OUTPUT 2" now supports streaming via FFmpeg. Just select "FFmpeg", "flv" and enter a URL like "rtmp://10.0.0.1/live/example" and you get an RTMP stream.
