### ISSUE TITLE
Is vingester supposed to enable headless NDI on the Mac?

### ISSUE THREAD

**Issue by chrismarquardt** [rse/vingester#2]
I can only seem to get the WIN mode to run, it says NO for NDI. Is there any additional tools required for this to work?

**Comment by chrismarquardt** [comment]
Never mind, I figured it out. Didn't realize you had to stop the stream and use the YES/NO field as a button, assumed it was a display instead of an active element. Maybe add a help button?

**Comment by rse** [comment]
Each element of the UI, including this button, has a tooltip which explains what it is. I hoped this is sufficient to see this help information when hoving over an element.
