### ISSUE TITLE
Projection to multiple displays identify displays incorrectly

### ISSUE THREAD

**Issue by JBraddockm** [rse/vingester#21]
I've just attached three and then four displays to a Displaylink Dock on my iMac. 

In the three display configuration, the +2,0 is not working as it also pushes to the +3,0 so the second display remains empty. Similarly, in four display configuration, +1,0 to display 2, +2,0 goes to display 3, +3,0 goes to display 4, and +4,0 goes to display 4.

Also, if the position fields are empty as in blank, the display projection doesn't work. It has to be set to 0, which makes sense but I think it also makes sense to set it 0 after the user deletes a previously set value.

Finally, is there a particular reason for rendering in 60fps? As I plan to use Vingester for OBS Ninja streams, which will be 30fps anyway, it seems that 30fps would suffice.

<img width="839" alt="image" src="https://user-images.githubusercontent.com/16445610/117441711-b7fafb00-af2d-11eb-96a4-a66d82a39cde.png">

**Comment by rse** [comment]
The display positioning calculation can be wrong. I've to check this. The default values for the position are a good suggestion and I'll implement this. The 60fps I cannot control: this is the native FPS of your display and cannot be changed. But for the Frameless mode, feel free to capture the windows will less FPS in your mixing and/or capturing software. The only thing Vingester CAN DO (and already does) is in Headless mode it skips frames in the NDI output. But in case of a 60fps display (the usual standard) the incoming fps is 60 and cannot be changed by Vingester.

**Comment by rse** [comment]
The default values on entering empty fields is now already implemented and will be available in version 2.0.0. The display calculation will be fixed next.

**Comment by rse** [comment]
Ok, I've now completely reimplemented the "display" field. Instead of a texual field, it is now a graphical toggle:

<img width="603" alt="image" src="https://user-images.githubusercontent.com/221273/118195465-91682300-b44b-11eb-8c26-f0c4bcb0daa8.png">

Will be available with Vingester 2.0.0.

**Comment by JBraddockm** [comment]
The misidentification still persists and it is unpredictable. It seems that the app gets confused about which one is Display 1, 2 etc. There is too many combinations so it is hard to say what causes the problem.

What I noticed:

- Sometimes, you have to cycle through display arrangement graphics in Vingestor to get the projection working correctly. But it is not certain.

- Creating a new browser entry does’t display graphical display interface. It shows the previous one as is 0. Restarting the app brings the interface back.

**Comment by rse** [comment]
Under what OS are you experiencing these problems? I tried it both under macOS and windows with 2 and 3 external displays. Can it be that perhaps you have an old configuration from a previous version if Vingester? In this case, yes, you might have to cycle once to let the old configuration parameter be changed. 

If the graphical display on new browser entries I've to check, this can be a bug.

**Comment by rse** [comment]
Ok, the bug on added/cloned browser entries not showing the graphical display is now fixed and will be available with Vingester 2.0.2. The other issue I've to still check out...

**Comment by rse** [comment]
Ok, the stumbling over old Vingester 1.x "Display" settings should be now also fixed.

**Comment by JBraddockm** [comment]
Not sure if this is an OS issue or something to do with the app or just the limitation of the app but the display numbering gets mixed up along the way.

I can connect the displays one by one and until the fourth display, the inputs in the ATEM match the BMD HDMI (1), etc numbering and after the fourth display, it gets mixed up. So it makes it quite difficult to guess what goes where.

For example;  

<img width="839" alt="image" src="https://user-images.githubusercontent.com/16445610/118277320-961aee80-b4c0-11eb-93bf-2f228f1d30da.png">

![image](https://user-images.githubusercontent.com/16445610/118277382-a501a100-b4c0-11eb-9b1a-a23734a2bcd9.png)

On ATEM, input 1 is active but the display information is BMD HDMI (2). So, choosing 1 in Vingester projects to input 2 on the ATEM.

On ATEM, input 2 is active but the display information is BMD HDMI (3). So, to target Input 2, I have to choose 1 in Vingester.

On ATEM, input 3 is active but the display information is BMD HDMI (4). So, to target Input 3, I have to choose 4 in Vingester.

On ATEM, input 4 is active but the display information is BMD HDMI (1). So, to target Input 4, I have to choose 3 in Vingester. 

This combination is not permanent and also changes.  

So it seems that targeting the displays with numbers in the app doesn't correspond to what's being reported as BMD HDMI 1, 2, etc in this case. This is why I think displaying the actual display information such as BMD HDMI (1) seems more accurate as it doesn't matter how the OS mixes these numbers and thus changes the input in ATEM, I can easily choose the correct one.

But as I understand from your previous answer, there are technical limitations to display this information.

I'll test it further and report back.
