### ISSUE TITLE
Feature Request: Interaction with headless browser

### ISSUE THREAD

**Issue by Seriousness** [rse/vingester#25]
It would be awesome to allow interaction with the headless browser. I'd be happy with some console access, like in the developer consoles of various browsers, so type some js and fire/change stuff. 

Other options could be to allow remote debug access with a chrome instance or at least load some custom js, too.

I could use this eg. to automate logins for pages that dont need other interaction and dismiss the overhead of the screen browser or some custom macros.

**Comment by rse** [comment]
The next version 2.0.0 certainly will allow you to inject CSS and JS. For additional interaction you could use both Frameless and Headless mode in parallel. The Frameless window for interaction, the Headless for sending the output out.

**Comment by rse** [comment]
Ok, for Vingester 2.0.0 (soon to be released) I've now added a "DevTools" button to each browser configuration which allows you to open a DevTools window and perform low-level interactions with the Web Contents.
