### ISSUE TITLE
I'm having issues receiving more than one source

### ISSUE THREAD

**Issue by Losvideo** [rse/vingester#31]
I'm using a strong gaming laptop for vingestor. I'm receiving in VMIX via NDI on my tower.
I'm using the sample config and only changing the relevant information for my session. 

I launch P01 and it comes in. It has the indicator with the "2" Indicating there are two connections. 
(this connection is from a Macbook pro via chrome).

I launch P02 and it does not come in. Indicator says there are "0" connections. (This connection was attempted thru a browser on my iPhone).
Then I tried connecting to P02 first and I received it. (using iPhone).
I then started P01 and there was no connection. (Using Macbook Pro as the source)

Thank you for your help.

[StreamBeans Main Test Room.zip](https://github.com/rse/vingester/files/6497677/StreamBeans.Main.Test.Room.zip)

**Comment by rse** [comment]
Your problem is that you are using the "Title" "StreamBeans_Ninja_Test_1" in both browser configurations. As the tooltip of the "Title" field explains, this title is used for the NDI stream name. Change it to different names and you should be able to receive two NDI streams.

**Comment by Losvideo** [comment]
Thank you for your help with this. 
I apologize for my misunderstanding. I will try this tomorrow, I’m sure it’ll work. 
I appreciate the assistance.


Kind regards,

Carlos





On May 31, 2021, at 5:37 PM, Dr. Ralf S. Engelschall ***@***.***> wrote:

﻿
Your problem is that you are using the "Title" "StreamBeans_Ninja_Test_1" in both browser configurations. As the tooltip of the "Title" field explains, this title is used for the NDI stream name. Change it to different names and you should be able to receive two NDI streams.
