### ISSUE TITLE
Syphon output

### ISSUE THREAD

**Issue by JBraddockm** [rse/vingester#32]
I was wondering if it is possible to have Syphon output from a browser source. 

I want for example take an instance from Singular Live and turn it into a Syphon output with transparency. I know that NDI can also work for this purpose but for some reasons I find NDI to be resource hungry compared to Syphon.

**Comment by rse** [comment]
Syphon is a macOS-only solution AFAIK. As Vingester is a cross-platform tool, adding Syphon support to Vingester IMHO makes just little sense (because it then would be available only under macOS).

**Comment by JBraddockm** [comment]
I think on Windows, there is [spout](https://spout.zeal.co) for the same purpose.

**Comment by rse** [comment]
I'm currently not planning to add such non-cross-platform functionalities to Vingester. Also, there is still no Spout-binding for Node.js, which means it cannot be integrated easily into an Electron-based technology like Vingester. So, I allow me to close this issue for now.
