### ISSUE TITLE
Live graphics simple integration (for test)

### ISSUE THREAD

**Issue by aloproducao** [rse/vingester#33]
Hi! I'm looking at ways to use vingester and have created a little experiment.

There was an adobe program called edge animate, it consists of an html animator using javascript through a graphical interface.

it is possible to generate an html page calling videos and with trigger, in the following example I made a video using after effects and rendered it in webm, with alpha channel 4444, vp8 codec,

by pressing the letter "A" on the keyboard the animation starts.

I'm working on small apps like these for intro, and animated lettering for use with vingester.

that way any design will be able to create layouts for their audio visual productions.
[experiment.zip](https://github.com/rse/vingester/files/6588166/experiment.zip)

**Comment by aloproducao** [comment]
here one video
https://user-images.githubusercontent.com/43450424/120570340-47d97b00-c3ee-11eb-98f0-6e78c7a333a6.mp4

**Comment by rse** [comment]
Neat, another way to create flexible live graphics and integrate them into video productions with the help of tools like Vingester...

**Comment by rse** [comment]
I've added a section to the Vingester guide to hint people also about this source of graphics: https://vingester.app/guide/#/sources?id=adobe-animate
