### ISSUE TITLE
win64-build: Uncaught Error: Cannot find module 'execa'

### ISSUE THREAD

**Issue by Brunhilde** [rse/vingester#34]
Win64-build of version 2.2.2 gives me an uncaught exception not finding the module execa. Version 2.2.1 is fine. Frameless mode seems to work, but NDI source is not showing up.

`[2021-06-03 23:51:54.341] [error]  (main)   browser/worker-4993D7EC: console: Uncaught Error: Cannot find module 'execa' Require stack: - C:\Users\....\AppData\Local\Temp\1tQwJX4ZtuAgbYjnTXqGQrBSm9Q\resources\app.asar\vingester-ffmpeg.js - C:\Users\...\AppData\Local\Temp\1tQwJX4ZtuAgbYjnTXqGQrBSm9Q\resources\app.asar\vingester-browser-worker.html`

**Comment by rse** [comment]
Ops, you're right: the dependencies seem to be broken. Will be fixed with 2.2.3.
