### ISSUE TITLE
Chromium 91.0.4472.77 vulnerabilities

### ISSUE THREAD

**Issue by me-vlad** [rse/vingester#37]
Vingester 2.2.6 includes Chromium 91.0.4472.77 that have some known security issues:
https://chromereleases.googleblog.com/2021/06/stable-channel-update-for-desktop.html

**Comment by me-vlad** [comment]
Looks like latest upstream release electron 13.1.2 not bumbed chromium version :(

**Comment by rse** [comment]
Yes, once an Electron version, which includes the fixed Chromium versions, is available, a new Vingester version will be released within a short timeframe, of course.

**Comment by rse** [comment]
Sorry, still no updated Electron versions available...

**Comment by me-vlad** [comment]
Electron bumped chromium version in v14.0.0-beta.1 , no changes in current stable v13
