### ISSUE TITLE
Simple instagram integration streaming

### ISSUE THREAD

**Issue by aloproducao** [rse/vingester#40]
Hello, again the project is getting bigger every day!

well i was looking for a simple streaming solution for instagram and i found this i made two  modifications in FFmpeg is able to play video files in instagram as live.

the other modification was to strip the file stream to generate stream mode and be able to capture a stream to instagram via node.js

it still doesn't have an interface, an integration may be interesting. Thanks

[https://github.com/ErAz7/stream-live-to-instagram](url)   <<<< ORIGINAL REPO

Little study of case:

Stream a file config.

`ffmpeg -re -i "${videoPath}" -c:a aac -c:v libx264 -vf "scale=w=720:h=450:force_original_aspect_ratio=1,pad=720:1280:(ow-iw)/2:(oh-ih)/2" -f flv "rtmps://live-upload.instagram.com:443/rtmp/${stream_key}"`,
			`() => killProcess(ffmpegProcess.pid)
		)`

Stream rtmp to instagram Frame ok config.
`ffmpeg -re -i "rtmp://188.166.126.51/live/tvcrio" -c:a aac -c:v libx264 -vf "scale=w=720:h=450:force_original_aspect_ratio=1,pad=720:1280:(ow-iw)/2:(oh-ih)/2" -f flv "rtmps://live-upload.instagram.com:443/rtmp/${stream_key}"`,
			`() => killProcess(ffmpegProcess.pid)
		)'

**Comment by rse** [comment]
I'm not sure whether I understand your particular issue. Vingester allows you to pass arbitrary CLI options to the underlying  FFmpeg process, so you should be able to directly stream to Instragram the way you describe. Just add all those necessary options to the corresponding field in the Vingester control UI. Or do I overlook something?

**Comment by aloproducao** [comment]
I would like to integrate this project I believe it is very useful because it generates an instagram rtmp key, it can be just a button "stream to instagram from file" and "stream to instagram from stream"

with the configuration above FFmpeg it already makes the screen adjustment to vertical.

**Comment by aloproducao** [comment]
Today the process to transmit from vingester to instagram requires external software to generate the rtmp key, this replaces the use of external software.
Thanks for the quick answers.

**Comment by rse** [comment]
Ok, I understand. You are talking about convenience and not about feasibility. But I've to confess that I do not want to include such a special support for Instagram for two reasons: (1) when I add Instagram it would be also requested to add YouTube, Vimeo, TikTok, whatever, too and (2) Vingester primarily is about INGESTING and not BROADCASTING. Even the FFmpeg integration technically also can be used for broadcasting the ingested content, it actually is intended for local or remote recording the ingested streams. For really broadcasting, use a mixing software like OBS Studio to first receive your content and then broadcast the results. So, please understand that for those reasons I do not plan to integrate such a module.
