### ISSUE TITLE
Issues with OBS window capture on Windows Server 2019

### ISSUE THREAD

**Issue by luisfontes** [rse/vingester#44]
Hi,

Around april I used Vingester for an online play and noticed that I couldn't upgrade to any version greater than 1.7 or OBS would not recognize the Vingester window on the window capture source. I thought this was related to Windows Server 2019, as I was using a VM for streaming, and didn't investigate further. Kept Vingester on 1.7 and produced the play, everything went smoothly.

Now I'm producing another play and set up the same structure I used before, a VM on Google Cloud with Windows Server 2019 plus a GPU. I downloaded the latest version of Vingester to test and got the same issue as before, the Vingester was not 'captured' by Window Capture (the Vingester window appears on the dropdown, but it seems like it's transparent, only the cursor shows). I tested the electron capture app and got the same issue. Then I noticed it might be related to Chromium, because OBS was not capturing my Chrome browser as well. I've made it work by disabling hardware acceleration on the Chrome browser, with hardware accel disabled OBS started to capture the Chrome window.

So… I would like to use the latest version of Vingester for this play and was wondering if Chromium hardware acceleration might be the issue, and if it could be disabled on Vingester. I've tested with Vingester's GPU Accel ON/OFF to no avail.

**Comment by rse** [comment]
I've tried Vingester 2.4.0 (based on Electron 13.1.7) under Windows 10 and with an NVIDIA graphics card and with and without GPU hardware acceleration I was able to capture the Vingester window in OBS Studio 27.0.1:

![image](https://user-images.githubusercontent.com/221273/126236476-adc42fb3-5e94-41c6-aa7e-d35e1f66b72d.png)

So, I guess this is related to your Windows Server 2019 VM and its particular kind of virtualized GPU. At least the "GPU" button in Vingester currently is the only way to disable GPU hardware acceleration of the underlying Electron/Chromium, as I don't know any alternative API for this. Are you really sure that Vingester's GPU support was disabled in your tests?
