### ISSUE TITLE
Donation or support

### ISSUE THREAD

**Issue by FlowingSPDG** [rse/vingester#46]
Hello, this is awesome!!
I was looking for tool that can apply customized-CSS to browser source for vMix(vMix does not support custom CSS).
This is perfect tool for my purpose, thanks a lot!

I am willing to support/donate this project because I think I will use this to our broadcast.
Is there any donation page or something?

Thank you!

**Comment by rse** [comment]
I'm glad Vingester can solve one of your challenges. I've enabled the "Sponsor" button on the https://github.com/rse/vingester, see the right hand side. Alternatively you can go directly to the Github Sponsoring page I've activated: https://github.com/sponsors/rse Thanks for your support!
