### ISSUE TITLE
NDI UYVY support

### ISSUE THREAD

**Issue by pierremestrez1976** [rse/vingester#51]
Hello,

Some NDI receiver doesn't support alpha channel, would it be possible to support NDI FourCC

NDIlib_FourCC_video_type_UYVY 

thanks,

Pierre

**Comment by rse** [comment]
Ok, in the next version 2.4.2 there is an NDI>Alpha field for disabling the alpha channel. Internally it uses BGRX instead of BGRA color format which in turn should force NDI to use a non-alpha channel based transmission. I hope this resolves this issue.

**Comment by pierremestrez1976** [comment]
Works super fine !
Thanks Dr.
