### ISSUE TITLE
version 2.6.2 is the last one that has worked for me

### ISSUE THREAD

**Issue by rogue-ronin** [rse/vingester#55]
Hi,

Love this app, but it recently stopped showing the windows -- literally nothing is displayed. I upgraded to 2.6.6, and then 2.6.7 - both put icons in the taskbar but the windows don't show up.

[hardinfo_report.txt](https://github.com/rse/vingester/files/7414776/hardinfo_report.txt)
[kaunoa.yaml.txt](https://github.com/rse/vingester/files/7414792/kaunoa.yaml.txt)

If I downgrade to version 2.6.2 it works. For the simple one-scene shows like attached I make an electroncapture using Steve Seguin's app, but I'd really like to keep using Vingester -- I have some more complex shows coming up.

I will downgrade again, so no pressure. Thank you for this app, it's great!

Aloha

PS: I just tried 2.6.3, 2.6.4 and 2.6.5 as well, same issue.

**Comment by rogue-ronin** [comment]
Just a bump to note that 2.7.0 also still does not work.

Aloha

**Comment by rse** [comment]
I've no Manjaro Linux at hand, but tested Vingester 2.8.0 under Ubuntu inside Windows's WSL and displaying to X410. It showed the Web contents in the window just fine. I allow me to close this issue for now. Just re-open if you still experience the problems under your particular Linux distribution.
