### ISSUE TITLE
NDI SDK version for Vingester and rse/grandiose

### ISSUE THREAD

**Issue by me-vlad** [rse/vingester#58]
Current NDI SDK ver. is 5.0.10
Please  bump NDI version in the rse/grandiose repo
Thanks!

**Comment by rse** [comment]
As far as I know the NDI SDK(!) is at 5.0.3, the NDI Tools(!) are at 5.0.11.1 (Windows) and 5.0.10.7 (macOS). As Vingester bundles the NDI SDK and Vingester 2.7.0 contains the NDI SDK version 5.0.3, we are now up-to-date.

**Comment by me-vlad** [comment]
Latest NDI SDK for Linux downloaded from https://downloads.ndi.tv/SDK/NDI_SDK_Linux/Install_NDI_SDK_v5_Linux.tar.gz
contains Version.txt with v5.0.10

> cat Version.txt 
NDI 2021-11-03 r127785 v5.0.10

**Comment by rse** [comment]
Yes, the NDI SDK has different versions for different OS. For Linux, you are right, it is at 5.0.10. But Vingester 2.7.0 indeed contains this version under Linux.
