### ISSUE TITLE
Releases flag as "virus detected"

### ISSUE THREAD

**Issue by nickgnat** [rse/vingester#59]
Not sure what's flagging your software releases as such, but I tried to download various Win x64 releases of Vingester (ranging from 2.6.7 all the way back to 2.4.1) and each one was flagged by Google Chrome as "Virus detected" causing the download to fail. I attempted to download these in Firefox and Edge as well, and had similar behavior -- Firefox allowed the download, but 7-Zip refuse to open the zip file on grounds of a virus detected, and Microsoft Defender promptly flagged and removed it. Edge refused to download as well, with a virus detected message. I'm unsure what within the zip files is flagging as a virus, but it is very hard to download and use the software with this behavoir.

**Comment by rse** [comment]
Yes, this is an issue with Windows Defender. It seems to be too aggressive and regularly flags Electron-Builder packed Electron apps like Vingester. On my system about two weeks ago I just had to update to the latest Windows Defender and such problems went away. So, can it be that you have not the latest Microsoft updates applied, too? I'll check again on my side once again...

As a workaround, as I can promise you there is no Malware inside Vingester (just check the source yourself, too) and it is just built with Electron-Builder, you can go the Windows system preferences under Security and make an exception for the `Vingester.exe` file. Yes, that's really nasty, but the only workaround I'm aware of.

As a second workaround, in case you have a development environment with Node.js installed (or install it from nodejs.org), you can download the Vingester sources and with `npm install` and `npm start` you can start a non-packaged version of Vingester.

**Comment by rse** [comment]
I've released Vingester 2.7.0, based on a newer Electron-Builder and the resulting binary at least under my Windows 10 (with latest Windows Defender) is at least not flagged. So, I hope this issue is resolved -- at least until a newer version of Windows Defender starts to flag those Electron-Builder binaries again...
