### ISSUE TITLE
M1 / Mac Arm Support

### ISSUE THREAD

**Issue by DrewLX** [rse/vingester#63]
I get a Dyld error when running this on M1 Pro:

`dyld[30511]: missing symbol called`

npm install completes fine, but I get this error upon npm start. Presumably, this is grandiose bringing in the SDK. I've worked through the code and can't figure out the exact issue but some of it is over my head!

**Comment by rse** [comment]
Unless there is a NDI SDK for ARM64 (M1), Grandiose cannot be used and hence Vingester cannot work under this platform.

**Comment by DrewLX** [comment]
Thanks for the super quick response. 

My understanding is that the SDK has been updated to run perfectly in Rosetta and native support is coming. 

There are examples of non-node/electron based apps using this, but I'm not sure how one would support it via Rosetta.

**Comment by rse** [comment]
As I still do not find any M1-related NDI SDK for downloading, so I allow me to close this issue for now. Once you can tell me where to find the M1 NDI SDK, I'll try to support it in Grandiose and then here in Vingester. Just re-open the issue at this time.
