### ISSUE TITLE
Windows Defender: Trojan:Win32/Tnega!ml

### ISSUE THREAD

**Issue by Seriousness** [rse/vingester#64]
After downloading the current Binary for Win64 the Defender shouts out and recognizes some Trojan:Win32/Tnega!ml

(https://go.microsoft.com/fwlink/?linkid=142185&name=Trojan:Win32/Tnega!ml&threatid=2147763770)

I'm pretty sure this is a false alarm, just curious.

**Comment by Seriousness** [comment]
Ran the file through VirusTotal resulted in several flags:
Alibaba; Trojan:Win32/Bulta.6d20e261
DrWeb: Trojan.Inject4.17497
Sangfor Engine Zero: Suspicious.Win32.Save.a

could be something Electron related.

**Comment by rse** [comment]
I've rolled a new version 2.7.1 which (at least under my Windows 11 21H2) does currently not cause any trouble.
