### ISSUE TITLE
Any chance to capture audio from each Vingester window?

### ISSUE THREAD

**Issue by Gabriele-LS** [rse/vingester#7]
Hello @rse. As I mentioned, my current workflow is based on multiple Chrome instances, each connected to a different participant in my show. Vingester might be a viable alternative, but I think it's missing one key feature: the ability to manage the incoming audio from the various windows as independent streams. With my current workflow, I can use Audio Hijack to capture each Chrome instance's audio (see screenshot). How could I do the same with Vingester?

<img width="930" alt="Screenshot 2021-04-09 at 07 59 26" src="https://user-images.githubusercontent.com/67373152/114136003-56357a00-990a-11eb-9b8b-fb2771d3a284.png">

**Comment by rse** [comment]
Interesting point. This is a duplicate issue to #5. I'll see what I can do...

**Comment by rse** [comment]
I've figured out how we can capture the audio of each frameless window in non-NDI situations and have it running for me. I've to still test this in more depth and cleanup my implementation, but expect one of the next versions (>= 1.5.0) to include this functionality.

**Comment by Gabriele-LS** [comment]
Wow! If you need me to test something, feel free to ask.

**Comment by rse** [comment]
This functionality is now available with Vingester version 1.5.0. Please give it a try.

**Comment by Gabriele-LS** [comment]
I just tested it… It works! Wonderful!

Is there any chance to define the output channels? The Dante Virtual Soundcard could be configured to have more than two output channels. It would be fantastic to have the ability to send the audio directly to a specific pair of channels without having to use an audio routing software like Loopback.

Anyway, great job, @rse! You are developing a superb little piece of software.

**Comment by rse** [comment]
Let me understand the request in more detail: you are not talking about the NUMBER of audio channels (which is already available) but the particular ASSIGNMENT of audio channels? So, you would like to send a stereo (channels 0+1) input to perhaps an output channels 4+5 or something like this?

**Comment by Gabriele-LS** [comment]
Exact. That's what I have to do new:

<img width="979" alt="Screenshot 2021-04-11 at 17 58 09" src="https://user-images.githubusercontent.com/67373152/114311576-a15cb200-9aef-11eb-9125-195e54ab1fee.png">

<img width="979" alt="Screenshot 2021-04-11 at 17 58 12" src="https://user-images.githubusercontent.com/67373152/114311581-a4f03900-9aef-11eb-9fd8-3311b21dab9b.png">

Two virtual audio interfaces that route the two Vingester browsers to two different pairs of channels. That way, I can have these channels available in my Dante network, I can send them to a mixer, or use them in a video mixing software.

**Comment by Gabriele-LS** [comment]
I made another screenshot to show you one of my use cases. Audio goes from Vingester to a 2-channel virtual audio interface, then it is routed to a 16-channel virtual audio interface, and then it goes into a software mixer.

<img width="1725" alt="Screenshot 2021-04-11 at 18 16 46" src="https://user-images.githubusercontent.com/67373152/114312415-e6ceae80-9af2-11eb-961e-b21b91ea30b4.png">

**Comment by rse** [comment]
Ok, understood. Thanks for the explanation. I've to check whether this is possible from within the Electron technology stack underlying Vingester. If it is possible, I'll try to implement it.

How would one to configure this inside Vingester? Instead of saying just "2" in the Channels field one perhaps can say "1:3,2:4" to tell Vingester that channel 1 of the Web Contents goes to channel 3 of the output device and channel 2 of the Web Contents goes to channel 4 of the output device? Something like this?

**Comment by Gabriele-LS** [comment]
That's how mimoLive manages that. I think it's a good way. But, of course, it could also work as you described.

<img width="503" alt="Screenshot 2021-04-11 at 20 29 14" src="https://user-images.githubusercontent.com/67373152/114316617-96f8e300-9b04-11eb-9c68-1f6ce6d7f835.png">

**Comment by rse** [comment]
But are there never more than 2 channels in any Web Contents? That was the reason why the Vingester "Channel" is an input field until now and not just a "none/mono/stereo" toggle...

**Comment by Gabriele-LS** [comment]
Indeed. The point is capturing multiple browser audio and sending it to a multichannel audio device. Let's suppose that I have 4 browser windows (B1, B2, B3 and B4) each of them outputting 2 audio channels (L and R). How can I send that audio into a mixer or into a recorder etc? I can use a 8-channel audio card (X). But I need to route the audio to the various channels of that card. Something like this:

B1.L -> X.1
B1.R -> X.2

B2.L -> X.3
B2.R -> X.4

B3.L -> X.5
B3.R -> X.6

B4.L -> X.7
B4.R -> X.8

**Comment by Gabriele-LS** [comment]
By the way, the possibility to choose the number of channels is available only if you use NDI output. That's why I did not take it into account. Maybe you are right, it could happen that a webpage outputs more than 2 audio channels. That never happened to me. And I don't know what would happen in that case.
